#Microservice B

###Dependence Spring
    1-eureka discovery client
		2-spring web
		3-Spring data JPA
		4-lombok
		5-OpenFeign
		6-PostgreSql
		7-Spring Heteoas
		8-Rest 
		9-Devtools

###Application.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
spring:
  cloud:
    config:
      import-check.enabled: false
  application:
    name: document-service
    discovery:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyseSelection
    username: xxxxxxx
    password: xxxxxxx
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


