#ServerConfig

###Dependence Spring
    1- config server

###Application
@EnableConfigServer

###Application.properties
server.port=8888
spring.cloud.config.server.git.uri=https://github.com/Mister-Ndiaye/mndiaye-server-config.git

